### ISSUE TITLE
use consistent jquery commands throughout the JavaScript

### ISSUE THREAD

**Issue by ryan-whit** [johnaslani/staffing#14]
There is currently a mix of plain JavaScript and JQuery throughout the .js file. Move all DOM commands to JQuery to ensure consistency.

This includes:
- [ ] DOM selection (e.g., `querySelector`)
- [ ] listening events (e.g., `addEventListener`
- [ ] and dynamic element creation

**Comment by johnaslani** [comment]
I move the DOM command to JQuery.

**Comment by ryan-whit** [comment]
Closed by John.
