### ISSUE TITLE
Determine if we should use album or track searches

### ISSUE THREAD

**Issue by ryan-whit** [johnaslani/staffing#17]
The album and track API endpoints for Napster are currently implemented but unused. Determine if we would like to include these endpoints, should we have time to implement them.

The results could be added to a new container in the HTML, or into another HTML page altogether.

Example here (click on a playlist): https://jsfiddle.net/napstercat/b9Lpavv9/

**Comment by johnaslani** [comment]
If this is more than minimum requirement, let's focus on what needs to be delivered.

**Comment by ryan-whit** [comment]
This a future feature we might want, but don't have time for.
