### ISSUE TITLE
Investige the use of a third API to use in the web page

### ISSUE THREAD

**Issue by ryan-whit** [johnaslani/staffing#20]
We are currently only using the Wiki API to provide a link to the wikipedia page. Determine if we should use an additional API to provide more information, and if so, implement that API into the current web page.

**Comment by johnaslani** [comment]
We might be able to provide some more information from Wiki if required to meet the criteria of using the second API. I think it takes some time to work on a new API.

**Comment by ryan-whit** [comment]
Won't do this for now.
