### ISSUE TITLE
Put together the project presentation

### ISSUE THREAD

**Issue by ryan-whit** [johnaslani/staffing#21]
Template: https://docs.google.com/presentation/d/10QaO9KH8HtUXj__81ve0SZcpO5DbMbqqQr4iPpbwKks/edit#slide=id.p

**Comment by johnaslani** [comment]
I'd be happy to create the presentation but I need the team inputs.

**Comment by ryan-whit** [comment]
Copied the presentation template to our shared drive. We can work on it these evening: https://docs.google.com/presentation/d/16KsvZljTEx182c46m3gYPrK4wiHs22_JHNZDVFPjTNg/edit#slide=id.p

**Comment by ryan-whit** [comment]
Done. Presentation here: https://docs.google.com/presentation/d/16KsvZljTEx182c46m3gYPrK4wiHs22_JHNZDVFPjTNg/edit#slide=id.p
